title: codenuke
description: Automated code review for reliable, trusted refactoring
url: https://codenuke.dev
theme: minima

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
